#!/bin/sh

#
# SparkPi Updater Script executed at start
#
#	The target system will have a /Updater directory. The files for an
#	update will be placed in a version subdirectory under /Updater. For instance, 
#	/Updater/1.0.1/
#	
#		scp -pr <local dir> wavest8.local:/Updater
#
#		will be the command to create the version subdirectory followed by the files updater
#		files. The updater files will consist of: 
#
#		/Updater/1.0.1/
#			install.info (mandatory)
#			pretar.sh (optional)
#			rootfs.tgz (optional)
#			posttar.sh (optional)
#	
#	Then, under /Updater will be a file pointing to the current intended version.
#	/Updater/CurrentInstallSource
#	
#	That file will contain the path of the installer files intended to be installed.
#	In the above example, it would simply contain "/Updater/1.0.1"
#

RootfsImageName=rootfs.tgz
RootfsMountPoint=/rootfs
BootMountPoint=$RootfsMountPoint/boot
KorgMountPoint=$RootfsMountPoint/Korg
EmmcBootPartition=/dev/mmcblk0p1
EmmcRootFsPartition=/dev/mmcblk0p2
EmmcKorgPartition=/dev/mmcblk0p3
InstallSourcePathFile=$RootfsMountPoint/Korg/Updater/CurrentInstallSourcePath

#----------------------------------------------------------
# ReEnableNormalBoot()
#----------------------------------------------------------
ReEnableNormalBoot()
{
	# ensure we reboot from the normal partition the next time around.
	echo "mounting boot partition"
	mkdir /boot
	mount /dev/mmcblk0p1 /boot 
	# double check in case the filesystem is slow to come up.
	# 	If it doesn't come up on the 3rd try, that's bad news.
	if [ ! -f /boot/config.txt ]; then
		sleep 2
		mount /dev/mmcblk0p1 /boot
		echo "waited two seconds for the EMMC"
		if [ ! -f /boot/config.txt ]; then
			sleep 4
			mount /dev/mmcblk0p1 /boot
			echo "waited four more seconds for the EMMC"
			if [ ! -f /boot/config.txt ]; then
				sleep 4
				mount /dev/mmcblk0p1 /boot
				echo "waited four more seconds even for the EMMC"
			fi
		fi
	fi
	echo "changing config.txt"
	cp /boot/config.txt /tmp/config.txt
	sed -i s/initramfs\ updater-scriptexecute.img/#initramfs\ updater-scriptexecute.img/ /tmp/config.txt
	sed -i s/kernel=\"updater-kernel/#kernel=\"updater-kernel/ /tmp/config.txt
	sync
	mv /tmp/config.txt /boot/config.txt
	sync
}

#----------------------------------------------------------
# RestartSystem()
#----------------------------------------------------------
RestartSystem()
{
	echo "preparing to reboot"
	sync
	reboot
}

#----------------------------------------------------------
# CheckUpdaterFiles()
#	takes one argument. $1 = UpdatePath
#----------------------------------------------------------
CheckUpdaterFiles()
{
	InstallInfoFile=$1/install.info
	if [ -e $InstallInfoFile ]; then
		while read filename md5checksum
		do
			if [ "$filename" != "VERSION" ] && [ "$filename" != "TIME_EST" ]; then
				echo "$filename" " : " "$md5checksum"
				fileToCheck=$1/$filename
				echo "checking $fileToCheck..."
				calculatedMd5=`md5sum $fileToCheck | awk '{print $1}'`
				if [ "$calculatedMd5" != "$md5checksum" ]; then
					echo "$filename checksum failure"
					RestartSystem
				fi
			fi
		done < "$InstallInfoFile"
	else
		echo "install.info file in $UpdatePath not found."
		RestartSystem
	fi
}


#----------------------------------------------------------
# Main body of the script
#----------------------------------------------------------
case "$1" in
  start)

	# restore boot partition for normal boot
	# Are there any conditions in which it makes more sense to wait to do this?
	# Assuming not, we immediately update the boot partition such that it will boot normally
	#	the next time the system is rebooted (either by power cycle, or the end of this process).
	sleep 3
	ReEnableNormalBoot

	uname -a
	ls -l /lib
	ls -l /usr/lib

	#make mount point directories and mount the emmc partition(s) to the mount point(s)
	mkdir -p $RootfsMountPoint
	mount $EmmcRootFsPartition $RootfsMountPoint
		# check return code to make sure the mount succeeded
		retVal=$?
		if [ $retVal -ne 0 ]; then
		    echo "Failed to mount the rootfs partition."
		fi
	mkdir -p $BootMountPoint
	mount $EmmcBootPartition $BootMountPoint
		# check return code to make sure the mount succeeded
		retVal=$?
		if [ $retVal -ne 0 ]; then
		    echo "Failed to mount the boot partition within the rootfs mount point."
		fi
	mkdir -p $KorgMountPoint
	mount $EmmcKorgPartition $KorgMountPoint
		# check return code to make sure the mount succeeded
		retVal=$?
		if [ $retVal -ne 0 ]; then
		    echo "Failed to mount the Korg partition within the rootfs mount point."
		fi

	# verify the existence of the CurrentInstallSourcePath file.
	if [ ! -f $InstallSourcePathFile ]; then
		echo "Required updater file $InstallSourcePathFile not found."
		RestartSystem
	fi

	# verify the path contained within that file exists
	UpdatePath=`awk '{print $1}' $InstallSourcePathFile`
	UpdatePath="$RootfsMountPoint/Korg$UpdatePath"
	if [ ! -d $UpdatePath ]; then
		echo "Path to update files not found. $UpdatePath"
		RestartSystem
	fi

	# read install.info from that path, verify checksums of files contained in the 
	#	install.info file (TODO: do sanity check of size requirements?)
	CheckUpdaterFiles $UpdatePath

	# run pretar.sh
	if [ -e $UpdatePath/pretar.sh ]; then
		sh $UpdatePath/pretar.sh > $RootfsMountPoint/errOutput1 2>&1
		sh $UpdatePath/pretar.sh
	fi

	# untar the files
	if [ -e $UpdatePath/rootfs.tgz ]; then
		# how to do the big tar here. Can we do a progress bar?
		echo "executing tar xvf $UpdatePath/rootfs.tgz -C $RootfsMountPoint"
		tar xvf $UpdatePath/rootfs.tgz -C $RootfsMountPoint
	fi

	# run posttar.sh
	if [ -e $UpdatePath/posttar.sh ]; then
		sh $UpdatePath/posttar.sh > $RootfsMountPoint/errOutput2 2>&1
		sh $UpdatePath/posttar.sh
	fi

	touch $UpdatePath/UpdateMCUs

	# reboot.
	RestartSystem
    ;;

  stop)
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
